sudo: false
language: go

cache: false
go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - openssl aes-256-cbc -K $encrypted_b7ac9c2fa755_key -iv $encrypted_b7ac9c2fa755_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - ssh-keyscan -H $MACHINE_ADDRESS >> ~/.ssh/known_hosts

install: true

before_script:
  - go mod tidy
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
    sh -s -- -b $(go env GOPATH)/bin v1.17.1

script:
  - go build -o main.o -i cmd/core/main.go
  - go test -v -race ./...
  - golangci-lint run -c config/.golangci.yml

deploy:
  - provider: script
    skip_cleanup: true
    script: bash script/deploy.sh
    on:
      branch: production
